module.exports = [
  { modelName: 'Boeing 737-800', manufacturer: 'Boeing', yearIntroduced: 1998, category: 'Civil', status: 'Active', country: 'United States', rangeKm: 3582, maxPassengersEfficiency: 189 },
  { modelName: 'Airbus A320-200', manufacturer: 'Airbus', yearIntroduced: 1988, category: 'Civil', status: 'Active', country: 'France', rangeKm: 3821, maxPassengersEfficiency: 180 },
  { modelName: 'Boeing 777-300ER', manufacturer: 'Boeing', yearIntroduced: 2004, category: 'Civil', status: 'Active', country: 'United States', rangeKm: 8482, maxPassengersEfficiency: 396 },
  { modelName: 'Airbus A350-900', manufacturer: 'Airbus', yearIntroduced: 2015, category: 'Civil', status: 'Active', country: 'France', rangeKm: 9321, maxPassengersEfficiency: 350 },
  { modelName: 'Boeing 787-9', manufacturer: 'Boeing', yearIntroduced: 2014, category: 'Civil', status: 'Active', country: 'United States', rangeKm: 8786, maxPassengersEfficiency: 296 },
  { modelName: 'Airbus A330-300', manufacturer: 'Airbus', yearIntroduced: 1994, category: 'Civil', status: 'Active', country: 'France', rangeKm: 7301, maxPassengersEfficiency: 300 },
  { modelName: 'Boeing 747-8I', manufacturer: 'Boeing', yearIntroduced: 2012, category: 'Civil', status: 'Limited Active', country: 'United States', rangeKm: 9206, maxPassengersEfficiency: 467 },
  { modelName: 'Airbus A380-800', manufacturer: 'Airbus', yearIntroduced: 2007, category: 'Civil', status: 'Active', country: 'France', rangeKm: 9445, maxPassengersEfficiency: 615 },
  { modelName: 'Embraer E190', manufacturer: 'Embraer', yearIntroduced: 2005, category: 'Civil', status: 'Active', country: 'Brazil', rangeKm: 2819, maxPassengersEfficiency: 114 },
  { modelName: 'Bombardier CRJ900', manufacturer: 'Bombardier', yearIntroduced: 2003, category: 'Civil', status: 'Active', country: 'Canada', rangeKm: 1787, maxPassengersEfficiency: 90 },
  { modelName: 'ATR 72-600', manufacturer: 'ATR', yearIntroduced: 2011, category: 'Civil', status: 'Active', country: 'France/Italy', rangeKm: 949, maxPassengersEfficiency: 78 },
  { modelName: 'De Havilland Dash 8 Q400', manufacturer: 'De Havilland Canada', yearIntroduced: 2000, category: 'Civil', status: 'Active', country: 'Canada', rangeKm: 1567, maxPassengersEfficiency: 90 },
  { modelName: 'Boeing 767-300ER', manufacturer: 'Boeing', yearIntroduced: 1988, category: 'Civil', status: 'Active', country: 'United States', rangeKm: 6879, maxPassengersEfficiency: 269 },
  { modelName: 'Airbus A321neo', manufacturer: 'Airbus', yearIntroduced: 2017, category: 'Civil', status: 'Active', country: 'France', rangeKm: 4598, maxPassengersEfficiency: 244 },
  { modelName: 'Boeing 737 MAX 8', manufacturer: 'Boeing', yearIntroduced: 2017, category: 'Civil', status: 'Active', country: 'United States', rangeKm: 4082, maxPassengersEfficiency: 210 },
  { modelName: 'Airbus A220-300', manufacturer: 'Airbus', yearIntroduced: 2016, category: 'Civil', status: 'Active', country: 'Canada', rangeKm: 3913, maxPassengersEfficiency: 149 },
  { modelName: 'Comac C919', manufacturer: 'Comac', yearIntroduced: 2023, category: 'Civil', status: 'Active', country: 'China', rangeKm: 3452, maxPassengersEfficiency: 192 },
  { modelName: 'Sukhoi Superjet 100', manufacturer: 'Sukhoi', yearIntroduced: 2011, category: 'Civil', status: 'Active', country: 'Russia', rangeKm: 2845, maxPassengersEfficiency: 108 },
  { modelName: 'Mitsubishi SpaceJet M90', manufacturer: 'Mitsubishi', yearIntroduced: 0, category: 'Civil', status: 'Program Halted', country: 'Japan', rangeKm: 2175, maxPassengersEfficiency: 92 },
  { modelName: 'Boeing 757-200', manufacturer: 'Boeing', yearIntroduced: 1983, category: 'Civil', status: 'Active', country: 'United States', rangeKm: 4488, maxPassengersEfficiency: 239 },
  { modelName: 'McDonnell Douglas MD-11', manufacturer: 'McDonnell Douglas', yearIntroduced: 1990, category: 'Civil', status: 'Freighter Active', country: 'United States', rangeKm: 7873, maxPassengersEfficiency: 323 },
  { modelName: 'Airbus A340-300', manufacturer: 'Airbus', yearIntroduced: 1993, category: 'Civil', status: 'Limited Active', country: 'France', rangeKm: 8389, maxPassengersEfficiency: 295 },
  { modelName: 'Concorde', manufacturer: 'Aérospatiale/BAC', yearIntroduced: 1976, category: 'Civil', status: 'Retired', country: 'France/United Kingdom', rangeKm: 4488, maxPassengersEfficiency: 128 },
  { modelName: 'Tupolev Tu-154', manufacturer: 'Tupolev', yearIntroduced: 1972, category: 'Civil', status: 'Limited Active', country: 'Soviet Union/Russia', rangeKm: 3281, maxPassengersEfficiency: 180 },
  { modelName: 'Ilyushin Il-96', manufacturer: 'Ilyushin', yearIntroduced: 1993, category: 'Civil', status: 'Limited Active', country: 'Russia', rangeKm: 6835, maxPassengersEfficiency: 300 },
  { modelName: 'Antonov An-148', manufacturer: 'Antonov', yearIntroduced: 2009, category: 'Civil', status: 'Limited Active', country: 'Ukraine', rangeKm: 2734, maxPassengersEfficiency: 85 },
  { modelName: 'Boeing 727-200', manufacturer: 'Boeing', yearIntroduced: 1967, category: 'Civil', status: 'Limited Active', country: 'United States', rangeKm: 2759, maxPassengersEfficiency: 189 },
  { modelName: 'Douglas DC-3', manufacturer: 'Douglas', yearIntroduced: 1936, category: 'Civil', status: 'Limited Active', country: 'United States', rangeKm: 1491, maxPassengersEfficiency: 32 },
  { modelName: 'Lockheed L-1011 TriStar', manufacturer: 'Lockheed', yearIntroduced: 1972, category: 'Civil', status: 'Retired', country: 'United States', rangeKm: 4598, maxPassengersEfficiency: 400 },
  { modelName: 'Fokker 100', manufacturer: 'Fokker', yearIntroduced: 1988, category: 'Civil', status: 'Active', country: 'Netherlands', rangeKm: 1970, maxPassengersEfficiency: 109 },
  { modelName: 'Cessna 172 Skyhawk', manufacturer: 'Cessna', yearIntroduced: 1956, category: 'Civil', status: 'Active', country: 'United States', rangeKm: 801, maxPassengersEfficiency: 4 },
  { modelName: 'Pilatus PC-12', manufacturer: 'Pilatus', yearIntroduced: 1994, category: 'Civil', status: 'Active', country: 'Switzerland', rangeKm: 2123, maxPassengersEfficiency: 9 },
  { modelName: 'Gulfstream G650', manufacturer: 'Gulfstream', yearIntroduced: 2012, category: 'Civil', status: 'Active', country: 'United States', rangeKm: 8055, maxPassengersEfficiency: 19 },
  { modelName: 'Dassault Falcon 8X', manufacturer: 'Dassault', yearIntroduced: 2016, category: 'Civil', status: 'Active', country: 'France', rangeKm: 7422, maxPassengersEfficiency: 16 },
  { modelName: 'Bombardier Global 7500', manufacturer: 'Bombardier', yearIntroduced: 2018, category: 'Civil', status: 'Active', country: 'Canada', rangeKm: 8861, maxPassengersEfficiency: 19 },
  { modelName: 'Learjet 75', manufacturer: 'Bombardier', yearIntroduced: 2013, category: 'Civil', status: 'Active', country: 'Canada', rangeKm: 2348, maxPassengersEfficiency: 9 },
  { modelName: 'F-16 Fighting Falcon', manufacturer: 'General Dynamics/Lockheed Martin', yearIntroduced: 1978, category: 'Military', status: 'Active', country: 'United States', rangeKm: 2622, maxPassengersEfficiency: 0 },
  { modelName: 'F-15 Eagle', manufacturer: 'McDonnell Douglas/Boeing', yearIntroduced: 1976, category: 'Military', status: 'Active', country: 'United States', rangeKm: 3480, maxPassengersEfficiency: 0 },
  { modelName: 'F/A-18E/F Super Hornet', manufacturer: 'Boeing', yearIntroduced: 1999, category: 'Military', status: 'Active', country: 'United States', rangeKm: 2069, maxPassengersEfficiency: 0 },
  { modelName: 'F-22 Raptor', manufacturer: 'Lockheed Martin', yearIntroduced: 2005, category: 'Military', status: 'Active', country: 'United States', rangeKm: 1839, maxPassengersEfficiency: 0 },
  { modelName: 'F-35 Lightning II', manufacturer: 'Lockheed Martin', yearIntroduced: 2015, category: 'Military', status: 'Active', country: 'United States', rangeKm: 1367, maxPassengersEfficiency: 0 },
  { modelName: 'A-10 Thunderbolt II', manufacturer: 'Fairchild Republic', yearIntroduced: 1977, category: 'Military', status: 'Active', country: 'United States', rangeKm: 2579, maxPassengersEfficiency: 0 },
  { modelName: 'B-52 Stratofortress', manufacturer: 'Boeing', yearIntroduced: 1955, category: 'Military', status: 'Active', country: 'United States', rangeKm: 8800, maxPassengersEfficiency: 0 },
  { modelName: 'B-1B Lancer', manufacturer: 'Rockwell', yearIntroduced: 1986, category: 'Military', status: 'Active', country: 'United States', rangeKm: 7456, maxPassengersEfficiency: 0 },
  { modelName: 'B-2 Spirit', manufacturer: 'Northrop Grumman', yearIntroduced: 1997, category: 'Military', status: 'Active', country: 'United States', rangeKm: 6905, maxPassengersEfficiency: 0 },
  { modelName: 'B-21 Raider', manufacturer: 'Northrop Grumman', yearIntroduced: 2027, category: 'Military', status: 'In Development', country: 'United States', rangeKm: 5779, maxPassengersEfficiency: 0 },
  { modelName: 'C-130 Hercules', manufacturer: 'Lockheed Martin', yearIntroduced: 1956, category: 'Military', status: 'Active', country: 'United States', rangeKm: 2361, maxPassengersEfficiency: 92 },
  { modelName: 'C-17 Globemaster III', manufacturer: 'Boeing', yearIntroduced: 1995, category: 'Military', status: 'Active', country: 'United States', rangeKm: 6462, maxPassengersEfficiency: 154 },
  { modelName: 'C-5M Super Galaxy', manufacturer: 'Lockheed Martin', yearIntroduced: 1970, category: 'Military', status: 'Active', country: 'United States', rangeKm: 5530, maxPassengersEfficiency: 270 },
  { modelName: 'KC-135 Stratotanker', manufacturer: 'Boeing', yearIntroduced: 1957, category: 'Military', status: 'Active', country: 'United States', rangeKm: 15006, maxPassengersEfficiency: 80 },
  { modelName: 'KC-46 Pegasus', manufacturer: 'Boeing', yearIntroduced: 2019, category: 'Military', status: 'Active', country: 'United States', rangeKm: 7351, maxPassengersEfficiency: 114 },
  { modelName: 'E-3 Sentry', manufacturer: 'Boeing', yearIntroduced: 1977, category: 'Military', status: 'Active', country: 'United States', rangeKm: 4603, maxPassengersEfficiency: 0 },
  { modelName: 'P-8 Poseidon', manufacturer: 'Boeing', yearIntroduced: 2013, category: 'Military', status: 'Active', country: 'United States', rangeKm: 4660, maxPassengersEfficiency: 0 },
  { modelName: 'U-2 Dragon Lady', manufacturer: 'Lockheed', yearIntroduced: 1957, category: 'Military', status: 'Active', country: 'United States', rangeKm: 6400, maxPassengersEfficiency: 0 },
  { modelName: 'SR-71 Blackbird', manufacturer: 'Lockheed', yearIntroduced: 1966, category: 'Military', status: 'Retired', country: 'United States', rangeKm: 3355, maxPassengersEfficiency: 0 },
  { modelName: 'AH-64 Apache', manufacturer: 'Boeing', yearIntroduced: 1986, category: 'Military', status: 'Active', country: 'United States', rangeKm: 298, maxPassengersEfficiency: 0 },
  { modelName: 'CH-47 Chinook', manufacturer: 'Boeing', yearIntroduced: 1962, category: 'Military', status: 'Active', country: 'United States', rangeKm: 460, maxPassengersEfficiency: 55 },
  { modelName: 'V-22 Osprey', manufacturer: 'Bell/Boeing', yearIntroduced: 2007, category: 'Military', status: 'Active', country: 'United States', rangeKm: 1011, maxPassengersEfficiency: 24 },
  { modelName: 'Eurofighter Typhoon', manufacturer: 'Eurofighter GmbH', yearIntroduced: 2003, category: 'Military', status: 'Active', country: 'Europe', rangeKm: 1802, maxPassengersEfficiency: 0 },
  { modelName: 'Dassault Rafale', manufacturer: 'Dassault', yearIntroduced: 2001, category: 'Military', status: 'Active', country: 'France', rangeKm: 2299, maxPassengersEfficiency: 0 },
  { modelName: 'Saab JAS 39 Gripen', manufacturer: 'Saab', yearIntroduced: 1996, category: 'Military', status: 'Active', country: 'Sweden', rangeKm: 1988, maxPassengersEfficiency: 0 },
  { modelName: 'Panavia Tornado', manufacturer: 'Panavia', yearIntroduced: 1979, category: 'Military', status: 'Limited Active', country: 'Europe', rangeKm: 864, maxPassengersEfficiency: 0 },
  { modelName: 'SEPECAT Jaguar', manufacturer: 'SEPECAT', yearIntroduced: 1973, category: 'Military', status: 'Limited Active', country: 'France/United Kingdom', rangeKm: 2190, maxPassengersEfficiency: 0 },
  { modelName: 'Mikoyan MiG-29', manufacturer: 'Mikoyan', yearIntroduced: 1983, category: 'Military', status: 'Active', country: 'Russia', rangeKm: 889, maxPassengersEfficiency: 0 },
  { modelName: 'Sukhoi Su-27', manufacturer: 'Sukhoi', yearIntroduced: 1985, category: 'Military', status: 'Active', country: 'Russia', rangeKm: 2193, maxPassengersEfficiency: 0 },
  { modelName: 'Sukhoi Su-30', manufacturer: 'Sukhoi', yearIntroduced: 1996, category: 'Military', status: 'Active', country: 'Russia', rangeKm: 1864, maxPassengersEfficiency: 0 },
  { modelName: 'Sukhoi Su-35', manufacturer: 'Sukhoi', yearIntroduced: 2014, category: 'Military', status: 'Active', country: 'Russia', rangeKm: 2237, maxPassengersEfficiency: 0 },
  { modelName: 'Sukhoi Su-57', manufacturer: 'Sukhoi', yearIntroduced: 2020, category: 'Military', status: 'Active', country: 'Russia', rangeKm: 2175, maxPassengersEfficiency: 0 },
  { modelName: 'Mikoyan MiG-31', manufacturer: 'Mikoyan', yearIntroduced: 1981, category: 'Military', status: 'Active', country: 'Russia', rangeKm: 1864, maxPassengersEfficiency: 0 },
  { modelName: 'Tupolev Tu-95', manufacturer: 'Tupolev', yearIntroduced: 1956, category: 'Military', status: 'Active', country: 'Russia', rangeKm: 9321, maxPassengersEfficiency: 0 },
  { modelName: 'Tupolev Tu-160', manufacturer: 'Tupolev', yearIntroduced: 1987, category: 'Military', status: 'Active', country: 'Russia', rangeKm: 7643, maxPassengersEfficiency: 0 },
  { modelName: 'Ilyushin Il-76', manufacturer: 'Ilyushin', yearIntroduced: 1974, category: 'Military', status: 'Active', country: 'Soviet Union/Russia', rangeKm: 3107, maxPassengersEfficiency: 225 },
  { modelName: 'Antonov An-124 Ruslan', manufacturer: 'Antonov', yearIntroduced: 1986, category: 'Military', status: 'Limited Active', country: 'Ukraine', rangeKm: 2983, maxPassengersEfficiency: 88 },
  { modelName: 'Antonov An-225 Mriya', manufacturer: 'Antonov', yearIntroduced: 1988, category: 'Military', status: 'Destroyed', country: 'Ukraine', rangeKm: 9569, maxPassengersEfficiency: 0 },
  { modelName: 'Xian Y-20', manufacturer: 'Xian Aircraft', yearIntroduced: 2016, category: 'Military', status: 'Active', country: 'China', rangeKm: 4847, maxPassengersEfficiency: 0 },
  { modelName: 'Chengdu J-20', manufacturer: 'Chengdu', yearIntroduced: 2017, category: 'Military', status: 'Active', country: 'China', rangeKm: 3418, maxPassengersEfficiency: 0 },
  { modelName: 'Shenyang J-16', manufacturer: 'Shenyang', yearIntroduced: 2015, category: 'Military', status: 'Active', country: 'China', rangeKm: 2423, maxPassengersEfficiency: 0 },
  { modelName: 'Shenyang J-15', manufacturer: 'Shenyang', yearIntroduced: 2013, category: 'Military', status: 'Active', country: 'China', rangeKm: 2175, maxPassengersEfficiency: 0 },
  { modelName: 'Chengdu J-10', manufacturer: 'Chengdu', yearIntroduced: 2006, category: 'Military', status: 'Active', country: 'China', rangeKm: 1150, maxPassengersEfficiency: 0 },
  { modelName: 'Harbin Z-20', manufacturer: 'Harbin Aircraft', yearIntroduced: 2019, category: 'Military', status: 'Active', country: 'China', rangeKm: 373, maxPassengersEfficiency: 12 },
  { modelName: 'Mitsubishi F-2', manufacturer: 'Mitsubishi', yearIntroduced: 2000, category: 'Military', status: 'Active', country: 'Japan', rangeKm: 518, maxPassengersEfficiency: 0 },
  { modelName: 'Kawasaki C-2', manufacturer: 'Kawasaki', yearIntroduced: 2016, category: 'Military', status: 'Active', country: 'Japan', rangeKm: 6089, maxPassengersEfficiency: 110 },
  { modelName: 'KAI FA-50', manufacturer: 'KAI', yearIntroduced: 2013, category: 'Military', status: 'Active', country: 'South Korea', rangeKm: 1150, maxPassengersEfficiency: 0 },
  { modelName: 'HAL Tejas', manufacturer: 'HAL', yearIntroduced: 2015, category: 'Military', status: 'Active', country: 'India', rangeKm: 1864, maxPassengersEfficiency: 0 },
  { modelName: 'HAL Dhruv', manufacturer: 'HAL', yearIntroduced: 2002, category: 'Military', status: 'Active', country: 'India', rangeKm: 391, maxPassengersEfficiency: 12 },
  { modelName: 'Embraer KC-390 Millennium', manufacturer: 'Embraer', yearIntroduced: 2019, category: 'Military', status: 'Active', country: 'Brazil', rangeKm: 3809, maxPassengersEfficiency: 80 },
  { modelName: 'Aermacchi MB-339', manufacturer: 'Aermacchi', yearIntroduced: 1979, category: 'Military', status: 'Active', country: 'Italy', rangeKm: 1311, maxPassengersEfficiency: 0 },
  { modelName: 'Alenia C-27J Spartan', manufacturer: 'Alenia', yearIntroduced: 2006, category: 'Military', status: 'Active', country: 'Italy', rangeKm: 1150, maxPassengersEfficiency: 60 },
  { modelName: 'Airbus A400M Atlas', manufacturer: 'Airbus', yearIntroduced: 2013, category: 'Military', status: 'Active', country: 'Europe', rangeKm: 5406, maxPassengersEfficiency: 116 },
  { modelName: 'BAE Hawk', manufacturer: 'BAE Systems', yearIntroduced: 1976, category: 'Military', status: 'Active', country: 'United Kingdom', rangeKm: 1566, maxPassengersEfficiency: 0 },
  { modelName: 'Avro Lancaster', manufacturer: 'Avro', yearIntroduced: 1942, category: 'Military', status: 'Retired', country: 'United Kingdom', rangeKm: 2531, maxPassengersEfficiency: 0 },
  { modelName: 'Supermarine Spitfire', manufacturer: 'Supermarine', yearIntroduced: 1938, category: 'Military', status: 'Retired', country: 'United Kingdom', rangeKm: 705, maxPassengersEfficiency: 0 },
  { modelName: 'Messerschmitt Bf 109', manufacturer: 'Messerschmitt', yearIntroduced: 1937, category: 'Military', status: 'Retired', country: 'Germany', rangeKm: 528, maxPassengersEfficiency: 0 },
  { modelName: 'Focke-Wulf Fw 190', manufacturer: 'Focke-Wulf', yearIntroduced: 1941, category: 'Military', status: 'Retired', country: 'Germany', rangeKm: 497, maxPassengersEfficiency: 0 },
  { modelName: 'North American P-51 Mustang', manufacturer: 'North American Aviation', yearIntroduced: 1942, category: 'Military', status: 'Retired', country: 'United States', rangeKm: 1650, maxPassengersEfficiency: 0 },
  { modelName: 'Vought F4U Corsair', manufacturer: 'Vought', yearIntroduced: 1942, category: 'Military', status: 'Retired', country: 'United States', rangeKm: 1013, maxPassengersEfficiency: 0 },
  { modelName: 'Grumman F-14 Tomcat', manufacturer: 'Grumman', yearIntroduced: 1974, category: 'Military', status: 'Retired/Active in Iran', country: 'United States', rangeKm: 1839, maxPassengersEfficiency: 0 },
  { modelName: 'McDonnell Douglas F-4 Phantom II', manufacturer: 'McDonnell Douglas', yearIntroduced: 1960, category: 'Military', status: 'Limited Active', country: 'United States', rangeKm: 1616, maxPassengersEfficiency: 0 },
  { modelName: 'Lockheed P-3 Orion', manufacturer: 'Lockheed', yearIntroduced: 1962, category: 'Military', status: 'Active', country: 'United States', rangeKm: 5592, maxPassengersEfficiency: 0 },
  { modelName: 'Cessna 208 Caravan', manufacturer: 'Cessna', yearIntroduced: 1984, category: 'Civil', status: 'Active', country: 'United States', rangeKm: 1232, maxPassengersEfficiency: 14 }
];
