module.exports = [
  { modelName: 'Boeing 737-800', manufacturer: 'Boeing', yearIntroduced: 1998, category: 'Civil', status: 'Active', country: 'United States', rangeKm: 5765, maxPassengersEfficiency: 189 },
  { modelName: 'Airbus A320-200', manufacturer: 'Airbus', yearIntroduced: 1988, category: 'Civil', status: 'Active', country: 'France', rangeKm: 6150, maxPassengersEfficiency: 180 },
  { modelName: 'Boeing 777-300ER', manufacturer: 'Boeing', yearIntroduced: 2004, category: 'Civil', status: 'Active', country: 'United States', rangeKm: 13650, maxPassengersEfficiency: 396 },
  { modelName: 'Airbus A350-900', manufacturer: 'Airbus', yearIntroduced: 2015, category: 'Civil', status: 'Active', country: 'France', rangeKm: 15000, maxPassengersEfficiency: 350 },
  { modelName: 'Boeing 787-9', manufacturer: 'Boeing', yearIntroduced: 2014, category: 'Civil', status: 'Active', country: 'United States', rangeKm: 14140, maxPassengersEfficiency: 296 },
  { modelName: 'Airbus A330-300', manufacturer: 'Airbus', yearIntroduced: 1994, category: 'Civil', status: 'Active', country: 'France', rangeKm: 11750, maxPassengersEfficiency: 300 },
  { modelName: 'Boeing 747-8I', manufacturer: 'Boeing', yearIntroduced: 2012, category: 'Civil', status: 'Limited Active', country: 'United States', rangeKm: 14815, maxPassengersEfficiency: 467 },
  { modelName: 'Airbus A380-800', manufacturer: 'Airbus', yearIntroduced: 2007, category: 'Civil', status: 'Active', country: 'France', rangeKm: 15200, maxPassengersEfficiency: 615 },
  { modelName: 'Embraer E190', manufacturer: 'Embraer', yearIntroduced: 2005, category: 'Civil', status: 'Active', country: 'Brazil', rangeKm: 4537, maxPassengersEfficiency: 114 },
  { modelName: 'Bombardier CRJ900', manufacturer: 'Bombardier', yearIntroduced: 2003, category: 'Civil', status: 'Active', country: 'Canada', rangeKm: 2876, maxPassengersEfficiency: 90 },
  { modelName: 'ATR 72-600', manufacturer: 'ATR', yearIntroduced: 2011, category: 'Civil', status: 'Active', country: 'France/Italy', rangeKm: 1528, maxPassengersEfficiency: 78 },
  { modelName: 'De Havilland Dash 8 Q400', manufacturer: 'De Havilland Canada', yearIntroduced: 2000, category: 'Civil', status: 'Active', country: 'Canada', rangeKm: 2522, maxPassengersEfficiency: 90 },
  { modelName: 'Boeing 767-300ER', manufacturer: 'Boeing', yearIntroduced: 1988, category: 'Civil', status: 'Active', country: 'United States', rangeKm: 11070, maxPassengersEfficiency: 269 },
  { modelName: 'Airbus A321neo', manufacturer: 'Airbus', yearIntroduced: 2017, category: 'Civil', status: 'Active', country: 'France', rangeKm: 7400, maxPassengersEfficiency: 244 },
  { modelName: 'Boeing 737 MAX 8', manufacturer: 'Boeing', yearIntroduced: 2017, category: 'Civil', status: 'Active', country: 'United States', rangeKm: 6570, maxPassengersEfficiency: 210 },
  { modelName: 'Airbus A220-300', manufacturer: 'Airbus', yearIntroduced: 2016, category: 'Civil', status: 'Active', country: 'Canada', rangeKm: 6297, maxPassengersEfficiency: 149 },
  { modelName: 'Comac C919', manufacturer: 'Comac', yearIntroduced: 2023, category: 'Civil', status: 'Active', country: 'China', rangeKm: 5555, maxPassengersEfficiency: 192 },
  { modelName: 'Sukhoi Superjet 100', manufacturer: 'Sukhoi', yearIntroduced: 2011, category: 'Civil', status: 'Active', country: 'Russia', rangeKm: 4578, maxPassengersEfficiency: 108 },
  { modelName: 'Mitsubishi SpaceJet M90', manufacturer: 'Mitsubishi', yearIntroduced: 0, category: 'Civil', status: 'Program Halted', country: 'Japan', rangeKm: 3500, maxPassengersEfficiency: 92 },
  { modelName: 'Boeing 757-200', manufacturer: 'Boeing', yearIntroduced: 1983, category: 'Civil', status: 'Active', country: 'United States', rangeKm: 7222, maxPassengersEfficiency: 239 },
  { modelName: 'McDonnell Douglas MD-11', manufacturer: 'McDonnell Douglas', yearIntroduced: 1990, category: 'Civil', status: 'Freighter Active', country: 'United States', rangeKm: 12670, maxPassengersEfficiency: 323 },
  { modelName: 'Airbus A340-300', manufacturer: 'Airbus', yearIntroduced: 1993, category: 'Civil', status: 'Limited Active', country: 'France', rangeKm: 13500, maxPassengersEfficiency: 295 },
  { modelName: 'Concorde', manufacturer: 'Aérospatiale/BAC', yearIntroduced: 1976, category: 'Civil', status: 'Retired', country: 'France/United Kingdom', rangeKm: 7222, maxPassengersEfficiency: 128 },
  { modelName: 'Tupolev Tu-154', manufacturer: 'Tupolev', yearIntroduced: 1972, category: 'Civil', status: 'Limited Active', country: 'Soviet Union/Russia', rangeKm: 5280, maxPassengersEfficiency: 180 },
  { modelName: 'Ilyushin Il-96', manufacturer: 'Ilyushin', yearIntroduced: 1993, category: 'Civil', status: 'Limited Active', country: 'Russia', rangeKm: 11000, maxPassengersEfficiency: 300 },
  { modelName: 'Antonov An-148', manufacturer: 'Antonov', yearIntroduced: 2009, category: 'Civil', status: 'Limited Active', country: 'Ukraine', rangeKm: 4400, maxPassengersEfficiency: 85 },
  { modelName: 'Boeing 727-200', manufacturer: 'Boeing', yearIntroduced: 1967, category: 'Civil', status: 'Limited Active', country: 'United States', rangeKm: 4440, maxPassengersEfficiency: 189 },
  { modelName: 'Douglas DC-3', manufacturer: 'Douglas', yearIntroduced: 1936, category: 'Civil', status: 'Limited Active', country: 'United States', rangeKm: 2400, maxPassengersEfficiency: 32 },
  { modelName: 'Lockheed L-1011 TriStar', manufacturer: 'Lockheed', yearIntroduced: 1972, category: 'Civil', status: 'Retired', country: 'United States', rangeKm: 7400, maxPassengersEfficiency: 400 },
  { modelName: 'Fokker 100', manufacturer: 'Fokker', yearIntroduced: 1988, category: 'Civil', status: 'Active', country: 'Netherlands', rangeKm: 3170, maxPassengersEfficiency: 109 },
  { modelName: 'Cessna 172 Skyhawk', manufacturer: 'Cessna', yearIntroduced: 1956, category: 'Civil', status: 'Active', country: 'United States', rangeKm: 1289, maxPassengersEfficiency: 4 },
  { modelName: 'Pilatus PC-12', manufacturer: 'Pilatus', yearIntroduced: 1994, category: 'Civil', status: 'Active', country: 'Switzerland', rangeKm: 3417, maxPassengersEfficiency: 9 },
  { modelName: 'Gulfstream G650', manufacturer: 'Gulfstream', yearIntroduced: 2012, category: 'Civil', status: 'Active', country: 'United States', rangeKm: 12964, maxPassengersEfficiency: 19 },
  { modelName: 'Dassault Falcon 8X', manufacturer: 'Dassault', yearIntroduced: 2016, category: 'Civil', status: 'Active', country: 'France', rangeKm: 11945, maxPassengersEfficiency: 16 },
  { modelName: 'Bombardier Global 7500', manufacturer: 'Bombardier', yearIntroduced: 2018, category: 'Civil', status: 'Active', country: 'Canada', rangeKm: 14260, maxPassengersEfficiency: 19 },
  { modelName: 'Learjet 75', manufacturer: 'Bombardier', yearIntroduced: 2013, category: 'Civil', status: 'Active', country: 'Canada', rangeKm: 3778, maxPassengersEfficiency: 9 },
  { modelName: 'F-16 Fighting Falcon', manufacturer: 'General Dynamics/Lockheed Martin', yearIntroduced: 1978, category: 'Military', status: 'Active', country: 'United States', rangeKm: 4220, maxPassengersEfficiency: 0 },
  { modelName: 'F-15 Eagle', manufacturer: 'McDonnell Douglas/Boeing', yearIntroduced: 1976, category: 'Military', status: 'Active', country: 'United States', rangeKm: 5600, maxPassengersEfficiency: 0 },
  { modelName: 'F/A-18E/F Super Hornet', manufacturer: 'Boeing', yearIntroduced: 1999, category: 'Military', status: 'Active', country: 'United States', rangeKm: 3330, maxPassengersEfficiency: 0 },
  { modelName: 'F-22 Raptor', manufacturer: 'Lockheed Martin', yearIntroduced: 2005, category: 'Military', status: 'Active', country: 'United States', rangeKm: 2960, maxPassengersEfficiency: 0 },
  { modelName: 'F-35 Lightning II', manufacturer: 'Lockheed Martin', yearIntroduced: 2015, category: 'Military', status: 'Active', country: 'United States', rangeKm: 2200, maxPassengersEfficiency: 0 },
  { modelName: 'A-10 Thunderbolt II', manufacturer: 'Fairchild Republic', yearIntroduced: 1977, category: 'Military', status: 'Active', country: 'United States', rangeKm: 4150, maxPassengersEfficiency: 0 },
  { modelName: 'B-52 Stratofortress', manufacturer: 'Boeing', yearIntroduced: 1955, category: 'Military', status: 'Active', country: 'United States', rangeKm: 14162, maxPassengersEfficiency: 0 },
  { modelName: 'B-1B Lancer', manufacturer: 'Rockwell', yearIntroduced: 1986, category: 'Military', status: 'Active', country: 'United States', rangeKm: 12000, maxPassengersEfficiency: 0 },
  { modelName: 'B-2 Spirit', manufacturer: 'Northrop Grumman', yearIntroduced: 1997, category: 'Military', status: 'Active', country: 'United States', rangeKm: 11112, maxPassengersEfficiency: 0 },
  { modelName: 'B-21 Raider', manufacturer: 'Northrop Grumman', yearIntroduced: 2027, category: 'Military', status: 'In Development', country: 'United States', rangeKm: 9300, maxPassengersEfficiency: 0 },
  { modelName: 'C-130 Hercules', manufacturer: 'Lockheed Martin', yearIntroduced: 1956, category: 'Military', status: 'Active', country: 'United States', rangeKm: 3800, maxPassengersEfficiency: 92 },
  { modelName: 'C-17 Globemaster III', manufacturer: 'Boeing', yearIntroduced: 1995, category: 'Military', status: 'Active', country: 'United States', rangeKm: 10400, maxPassengersEfficiency: 154 },
  { modelName: 'C-5M Super Galaxy', manufacturer: 'Lockheed Martin', yearIntroduced: 1970, category: 'Military', status: 'Active', country: 'United States', rangeKm: 8900, maxPassengersEfficiency: 270 },
  { modelName: 'KC-135 Stratotanker', manufacturer: 'Boeing', yearIntroduced: 1957, category: 'Military', status: 'Active', country: 'United States', rangeKm: 24150, maxPassengersEfficiency: 80 },
  { modelName: 'KC-46 Pegasus', manufacturer: 'Boeing', yearIntroduced: 2019, category: 'Military', status: 'Active', country: 'United States', rangeKm: 11830, maxPassengersEfficiency: 114 },
  { modelName: 'E-3 Sentry', manufacturer: 'Boeing', yearIntroduced: 1977, category: 'Military', status: 'Active', country: 'United States', rangeKm: 7408, maxPassengersEfficiency: 0 },
  { modelName: 'P-8 Poseidon', manufacturer: 'Boeing', yearIntroduced: 2013, category: 'Military', status: 'Active', country: 'United States', rangeKm: 7500, maxPassengersEfficiency: 0 },
  { modelName: 'U-2 Dragon Lady', manufacturer: 'Lockheed', yearIntroduced: 1957, category: 'Military', status: 'Active', country: 'United States', rangeKm: 10300, maxPassengersEfficiency: 0 },
  { modelName: 'SR-71 Blackbird', manufacturer: 'Lockheed', yearIntroduced: 1966, category: 'Military', status: 'Retired', country: 'United States', rangeKm: 5400, maxPassengersEfficiency: 0 },
  { modelName: 'AH-64 Apache', manufacturer: 'Boeing', yearIntroduced: 1986, category: 'Military', status: 'Active', country: 'United States', rangeKm: 480, maxPassengersEfficiency: 0 },
  { modelName: 'CH-47 Chinook', manufacturer: 'Boeing', yearIntroduced: 1962, category: 'Military', status: 'Active', country: 'United States', rangeKm: 741, maxPassengersEfficiency: 55 },
  { modelName: 'V-22 Osprey', manufacturer: 'Bell/Boeing', yearIntroduced: 2007, category: 'Military', status: 'Active', country: 'United States', rangeKm: 1627, maxPassengersEfficiency: 24 },
  { modelName: 'Eurofighter Typhoon', manufacturer: 'Eurofighter GmbH', yearIntroduced: 2003, category: 'Military', status: 'Active', country: 'Europe', rangeKm: 2900, maxPassengersEfficiency: 0 },
  { modelName: 'Dassault Rafale', manufacturer: 'Dassault', yearIntroduced: 2001, category: 'Military', status: 'Active', country: 'France', rangeKm: 3700, maxPassengersEfficiency: 0 },
  { modelName: 'Saab JAS 39 Gripen', manufacturer: 'Saab', yearIntroduced: 1996, category: 'Military', status: 'Active', country: 'Sweden', rangeKm: 3200, maxPassengersEfficiency: 0 },
  { modelName: 'Panavia Tornado', manufacturer: 'Panavia', yearIntroduced: 1979, category: 'Military', status: 'Limited Active', country: 'Europe', rangeKm: 1390, maxPassengersEfficiency: 0 },
  { modelName: 'SEPECAT Jaguar', manufacturer: 'SEPECAT', yearIntroduced: 1973, category: 'Military', status: 'Limited Active', country: 'France/United Kingdom', rangeKm: 3524, maxPassengersEfficiency: 0 },
  { modelName: 'Mikoyan MiG-29', manufacturer: 'Mikoyan', yearIntroduced: 1983, category: 'Military', status: 'Active', country: 'Russia', rangeKm: 1430, maxPassengersEfficiency: 0 },
  { modelName: 'Sukhoi Su-27', manufacturer: 'Sukhoi', yearIntroduced: 1985, category: 'Military', status: 'Active', country: 'Russia', rangeKm: 3530, maxPassengersEfficiency: 0 },
  { modelName: 'Sukhoi Su-30', manufacturer: 'Sukhoi', yearIntroduced: 1996, category: 'Military', status: 'Active', country: 'Russia', rangeKm: 3000, maxPassengersEfficiency: 0 },
  { modelName: 'Sukhoi Su-35', manufacturer: 'Sukhoi', yearIntroduced: 2014, category: 'Military', status: 'Active', country: 'Russia', rangeKm: 3600, maxPassengersEfficiency: 0 },
  { modelName: 'Sukhoi Su-57', manufacturer: 'Sukhoi', yearIntroduced: 2020, category: 'Military', status: 'Active', country: 'Russia', rangeKm: 3500, maxPassengersEfficiency: 0 },
  { modelName: 'Mikoyan MiG-31', manufacturer: 'Mikoyan', yearIntroduced: 1981, category: 'Military', status: 'Active', country: 'Russia', rangeKm: 3000, maxPassengersEfficiency: 0 },
  { modelName: 'Tupolev Tu-95', manufacturer: 'Tupolev', yearIntroduced: 1956, category: 'Military', status: 'Active', country: 'Russia', rangeKm: 15000, maxPassengersEfficiency: 0 },
  { modelName: 'Tupolev Tu-160', manufacturer: 'Tupolev', yearIntroduced: 1987, category: 'Military', status: 'Active', country: 'Russia', rangeKm: 12300, maxPassengersEfficiency: 0 },
  { modelName: 'Ilyushin Il-76', manufacturer: 'Ilyushin', yearIntroduced: 1974, category: 'Military', status: 'Active', country: 'Soviet Union/Russia', rangeKm: 5000, maxPassengersEfficiency: 225 },
  { modelName: 'Antonov An-124 Ruslan', manufacturer: 'Antonov', yearIntroduced: 1986, category: 'Military', status: 'Limited Active', country: 'Ukraine', rangeKm: 4800, maxPassengersEfficiency: 88 },
  { modelName: 'Antonov An-225 Mriya', manufacturer: 'Antonov', yearIntroduced: 1988, category: 'Military', status: 'Destroyed', country: 'Ukraine', rangeKm: 15400, maxPassengersEfficiency: 0 },
  { modelName: 'Xian Y-20', manufacturer: 'Xian Aircraft', yearIntroduced: 2016, category: 'Military', status: 'Active', country: 'China', rangeKm: 7800, maxPassengersEfficiency: 0 },
  { modelName: 'Chengdu J-20', manufacturer: 'Chengdu', yearIntroduced: 2017, category: 'Military', status: 'Active', country: 'China', rangeKm: 5500, maxPassengersEfficiency: 0 },
  { modelName: 'Shenyang J-16', manufacturer: 'Shenyang', yearIntroduced: 2015, category: 'Military', status: 'Active', country: 'China', rangeKm: 3900, maxPassengersEfficiency: 0 },
  { modelName: 'Shenyang J-15', manufacturer: 'Shenyang', yearIntroduced: 2013, category: 'Military', status: 'Active', country: 'China', rangeKm: 3500, maxPassengersEfficiency: 0 },
  { modelName: 'Chengdu J-10', manufacturer: 'Chengdu', yearIntroduced: 2006, category: 'Military', status: 'Active', country: 'China', rangeKm: 1850, maxPassengersEfficiency: 0 },
  { modelName: 'Harbin Z-20', manufacturer: 'Harbin Aircraft', yearIntroduced: 2019, category: 'Military', status: 'Active', country: 'China', rangeKm: 600, maxPassengersEfficiency: 12 },
  { modelName: 'Mitsubishi F-2', manufacturer: 'Mitsubishi', yearIntroduced: 2000, category: 'Military', status: 'Active', country: 'Japan', rangeKm: 834, maxPassengersEfficiency: 0 },
  { modelName: 'Kawasaki C-2', manufacturer: 'Kawasaki', yearIntroduced: 2016, category: 'Military', status: 'Active', country: 'Japan', rangeKm: 9800, maxPassengersEfficiency: 110 },
  { modelName: 'KAI FA-50', manufacturer: 'KAI', yearIntroduced: 2013, category: 'Military', status: 'Active', country: 'South Korea', rangeKm: 1850, maxPassengersEfficiency: 0 },
  { modelName: 'HAL Tejas', manufacturer: 'HAL', yearIntroduced: 2015, category: 'Military', status: 'Active', country: 'India', rangeKm: 3000, maxPassengersEfficiency: 0 },
  { modelName: 'HAL Dhruv', manufacturer: 'HAL', yearIntroduced: 2002, category: 'Military', status: 'Active', country: 'India', rangeKm: 630, maxPassengersEfficiency: 12 },
  { modelName: 'Embraer KC-390 Millennium', manufacturer: 'Embraer', yearIntroduced: 2019, category: 'Military', status: 'Active', country: 'Brazil', rangeKm: 6130, maxPassengersEfficiency: 80 },
  { modelName: 'Aermacchi MB-339', manufacturer: 'Aermacchi', yearIntroduced: 1979, category: 'Military', status: 'Active', country: 'Italy', rangeKm: 2110, maxPassengersEfficiency: 0 },
  { modelName: 'Alenia C-27J Spartan', manufacturer: 'Alenia', yearIntroduced: 2006, category: 'Military', status: 'Active', country: 'Italy', rangeKm: 1850, maxPassengersEfficiency: 60 },
  { modelName: 'Airbus A400M Atlas', manufacturer: 'Airbus', yearIntroduced: 2013, category: 'Military', status: 'Active', country: 'Europe', rangeKm: 8700, maxPassengersEfficiency: 116 },
  { modelName: 'BAE Hawk', manufacturer: 'BAE Systems', yearIntroduced: 1976, category: 'Military', status: 'Active', country: 'United Kingdom', rangeKm: 2520, maxPassengersEfficiency: 0 },
  { modelName: 'Avro Lancaster', manufacturer: 'Avro', yearIntroduced: 1942, category: 'Military', status: 'Retired', country: 'United Kingdom', rangeKm: 4073, maxPassengersEfficiency: 0 },
  { modelName: 'Supermarine Spitfire', manufacturer: 'Supermarine', yearIntroduced: 1938, category: 'Military', status: 'Retired', country: 'United Kingdom', rangeKm: 1135, maxPassengersEfficiency: 0 },
  { modelName: 'Messerschmitt Bf 109', manufacturer: 'Messerschmitt', yearIntroduced: 1937, category: 'Military', status: 'Retired', country: 'Germany', rangeKm: 850, maxPassengersEfficiency: 0 },
  { modelName: 'Focke-Wulf Fw 190', manufacturer: 'Focke-Wulf', yearIntroduced: 1941, category: 'Military', status: 'Retired', country: 'Germany', rangeKm: 800, maxPassengersEfficiency: 0 },
  { modelName: 'North American P-51 Mustang', manufacturer: 'North American Aviation', yearIntroduced: 1942, category: 'Military', status: 'Retired', country: 'United States', rangeKm: 2655, maxPassengersEfficiency: 0 },
  { modelName: 'Vought F4U Corsair', manufacturer: 'Vought', yearIntroduced: 1942, category: 'Military', status: 'Retired', country: 'United States', rangeKm: 1630, maxPassengersEfficiency: 0 },
  { modelName: 'Grumman F-14 Tomcat', manufacturer: 'Grumman', yearIntroduced: 1974, category: 'Military', status: 'Retired/Active in Iran', country: 'United States', rangeKm: 2960, maxPassengersEfficiency: 0 },
  { modelName: 'McDonnell Douglas F-4 Phantom II', manufacturer: 'McDonnell Douglas', yearIntroduced: 1960, category: 'Military', status: 'Limited Active', country: 'United States', rangeKm: 2600, maxPassengersEfficiency: 0 },
  { modelName: 'Lockheed P-3 Orion', manufacturer: 'Lockheed', yearIntroduced: 1962, category: 'Military', status: 'Active', country: 'United States', rangeKm: 9000, maxPassengersEfficiency: 0 },
  { modelName: 'Cessna 208 Caravan', manufacturer: 'Cessna', yearIntroduced: 1984, category: 'Civil', status: 'Active', country: 'United States', rangeKm: 1982, maxPassengersEfficiency: 14 }
];
